allOf:
  - $ref: '#/components/schemas/ServiceKey'
  - type: object
    required:
      - attributes
    properties:
      attributes:
        type: object
        required:
          - url
          - port
          - name
          - rule
        properties:
          url:
            type: string
            example: 'http://example-service'
          port:
            type: string
            example: 80
          healthcheck_timout:
            type: string
            default: "3s"
            description: defines how much time Traefik will wait for the [200;300) answer from the server before deleting it from routing tables. Default value is 3s. This value cannot be updated
          healthcheck_interval:
            type: string
            default: "10s"
            description: defines how often Traefik should check service's health. Default value is 10s. This value cannot be updated
          name:
            type: string
            example: example-service
          rule:
            type: string
            example: Path(`/example`) || Path (`/example2`)
          rule_priority:
            type: integer
            example: 1
            description: priority of the passed rule which will override default rule priority in Traefik. Default priority is len(rule).
