allOf:
  - $ref: '#/components/schemas/ServiceKey'
  - type: object
    required:
      - attributes
    properties:
      attributes:
        type: object
        required:
          - url
          - port
          - name
          - rule
        properties:
          url:
            type: string
            example: 'http://example-service'
          port:
            type: string
            example: 80
          name:
            type: string
            example: example-service
          rule:
            type: string
            example: Path(`/example`) || Path (`/example2`)
          rule_priority:
            type: integer
            example: 1
            description: priority of the passed rule which will override default rule priority in Traefik. Default priority is len(rule).
